### ISSUE TITLE
Setting an empty value on a dynamic collection doesn't update the relationship

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#18]
Let's say we have a Club class and a Player class and we create a dynamic relationship between them called players. We add a new player to that collection and GORM creates the right relationship. But after that you set that collection to empty [], then GORM creates a new empty simple property with the same name as the relationship and leaves that relationship untouched.
If you tried to set the dynamic property again, it wouldn't work anymore.

**Comment by mburak** [comment]
You can see that behavior in this project: https://github.com/mburak/neo4j-app
In bootstrap we are setting clubs with a dynamic property called 'captains'. We set 2 captains for every club. After that we set barcelona's captains to be empty.
If you access the db after that you will see that there's a new property called 'captains' which is empty and it kept the old 'captains' relationships.

**Comment by graemerocher** [comment]
I implemented a fix, but it requires calling `foo.bars.clear()`. Doing `foo.bars = []` will not work as it replaces the dirty checking aware collection with a new collection. I don't see a way to support the latter at this stage.

**Comment by mburak** [comment]
The problem persists using clear(). It's little bit better because it's cleaning the relationships, but the empty property is still there so the next time it doesn't create the relationship when we add a new one.
Here you can see that empty "captains" property:
 
```
neo4j-sh (?)$ ls -a 69
:Club
*__id__      =[1550768939390967808]
*captains    =
*dateCreated =[1475684043942]
*lastUpdated =[1475684043942]
*name        =[FC Barcelona]
*version     =[1]
(FC Barcelona,69)-[:rival]->(Real Madrid CF,68)
(FC Barcelona,69)<-[:CLUB]-(Messi,83)
(FC Barcelona,69)<-[:CLUB]-(Ronaldo,82)
(FC Barcelona,69)<-[:CLUB]-(Neymar,84)
(FC Barcelona,69)-[:COUNTRY]->(Argentina,1)
(FC Barcelona,69)-[:LEAGUE]->(Spanish Liga,67)
(FC Barcelona,69)-[:captain]->(Ronaldo,82)
 ```

**Comment by mburak** [comment]
Hi @graemerocher, did you see this last comment? We still seeing the issue.

**Comment by mburak** [comment]
@graemerocher I think this should be reopened, I still see this behavior.

**Comment by graemerocher** [comment]
Provide an example please

**Comment by mburak** [comment]
It's in that sample project I provided in a previous comment: https://github.com/mburak/neo4j-app
